### ISSUE TITLE
Opening Project in Unity

### ISSUE THREAD

**Issue by crumbj** [bah8892/ErgoWitness#20]
Hello,
Do you have any documentation with regards to setting up the project in Unity? I noticed there are web pages, but I think I am missing a step to actually get the project opened with Unity.

**Comment by BenjaFriend** [comment]
You just have to open up the folder `ErgoWitness_Unity_5.6`... 

I would suggest that you take a look at the [Unity Docs](https://docs.unity3d.com/Manual/UnityOverview.html) if you have any other issues with opening the project or getting started with Unity
